# Generated by Django 6.0.1 on 2026-01-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(default='Admin', max_length=150),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
