# Generated by Django 6.0.1 on 2026-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_adminprofile_is_admin_adminprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='doctors/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
